services: 
  django: 
    build: mynt 
    command: gunicorn mynt.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/mynt/staticfiles
      - media_volume:/home/app/mynt/mediafiles
    expose: 
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/mynt/staticfiles
      - media_volume:/home/app/mynt/mediafiles
    ports:
      - 80:80
      - 8000:8000
    depends_on:
      - django


volumes:
  static_volume:
  media_volume: