# Generated by Django 5.0.3 on 2024-05-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='desc',
        ),
    ]
