# Generated by Django 5.0.3 on 2024-05-31 18:11

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_post_content_remove_profile_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
