# Generated by Django 5.0.6 on 2024-11-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_date_post_last_modifies_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
